### ISSUE TITLE
Need to wait for the DB to settle on startup

### ISSUE THREAD

**Issue by atdotio** [HrBingR/BookHaven#4]
When starting up the application (at least for the first time) via Docker, the stack needs to wait for the database to be initialized. Currently, database migrations attempt to run before the database is ready to accept connections. The compose.yml includes a `depends_on` clause, but that does not wait for the DB engine to initialize and reach a state where it will accept connections. Instead, adding a condition on the `depends_on` clause and a `healthcheck` command on the DB container causes the application to wait until the database is ready. 

The error message that appears in the logs looks something like this:
```
bookhaven    | time=2025-02-15T02:47:41 level=ERROR msg="Database error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")
bookhaven    | (Background on this error at: https://sqlalche.me/e/20/e3q8)"
bookhaven    | time=2025-02-15T02:47:41 level=ERROR msg="Original error: (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")"
bookhaven    | Database migrations failed, exiting.
bookhaven exited with code 1
```

A working `depends_on` configuration with associated MySQL `healthcheck`:
```
services:
  mysql:
    container_name: bookhaven-mysql
    [... snip ...]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  bookhaven:
    container_name: bookhaven
    [... snip ...]
    depends_on:
      mysql:
        condition: service_healthy
```
